CREATE TABLE IF NOT EXISTS `memo` (
  `id` INTEGER UNSIGNED PRIMARY KEY AUTOINCREMENT,
  `title` TEXT NOT NULL,
  `content` TEXT NOT NULL,
  `is_deleted` BOOLEAN NOT NULL DEFAULT FALSE,
  `created_at` INTEGER UNSIGNED NOT NULL,
  `updated_at` INTEGER UNSIGNED NOT NULL,
  `update_count` INTEGER UNSIGNED DEFAULT 1
);

CREATE TABLE IF NOT EXISTS `folder` (
  `id` INTEGER UNSIGNED PRIMARY KEY AUTOINCREMENT,
  `name` TEXT NOT NULL,
  `created_at` INTEGER UNSIGNED NOT NULL,
  `updated_at` INTEGER UNSIGNED NOT NULL,
  `update_count` INTEGER UNSIGNED DEFAULT 1
);

CREATE TABLE IF NOT EXISTS `memo_folder` (
  `memo_id` INTEGER UNSIGNED NOT NULL,
  `folder_id` INTEGER UNSIGNED NOT NULL,
  `memo_position` INTEGER UNSIGNED NOT NULL,
  `created_at` INTEGER UNSIGNED NOT NULL,
  `updated_at` INTEGER UNSIGNED NOT NULL,
  `update_count` INTEGER UNSIGNED DEFAULT 1,
  PRIMARY KEY (`memo_id`, `folder_id`, `memo_position`)
);
